# Generated by Django 4.0 on 2021-12-24 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_user'),
        ('documents', '0002_document_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employees.employee'),
            preserve_default=False,
        ),
    ]
