# Generated by Django 4.0 on 2021-12-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
