# Generated by Django 4.0 on 2021-12-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime_register', '0002_overtimeregister_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeregister',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
